#include "farversion.hpp"

#define PLUGIN_BUILD 9
#define PLUGIN_DESC L"far4j plugin"
#define PLUGIN_NAME L"far4j"
#define PLUGIN_FILENAME L"far4j.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
